### ISSUE TITLE
configurable Docker-Root-Directory

### ISSUE THREAD

**Issue by burgerTo** [microsoft/vs-azure-iot-edge-docs#10]
Hi, 

in our project, we want to use iot-edge-tools to develop different edge-modules. Some of these modules references against common libs which are also included as projects into the Edge solutions. 

Our solution structure of the Edge Project in Visual studio looks like: 

-IoT-Edge-Solution.sln
--| - Edge-Project
------| - Edge-Projet.iotedgeproj
--| - SharedNetCorelib (donet shared library)
------| - SharedNetCorelib.csproject
--| - Edge-Module1 (Edge Project) -> References SharedNetCoreLib
------| - Edge-Module1.csproject
------| - module.json
------| - DockerFile.amd64

The problem occurs now during the DockerBuild. We need to copy the sharedNetCore sourcecode into the Docker-Build-Image: 

COPY ["../SharedNetCorelib/SharedNetCorelib.csproj", "SharedNetCorelib/"]

This copy command fails, because pathes out of the Docker-Working-Directory are not allowded. 
It looks like, that the iot-edge-tools assumes the location of the Edge-Module1.csproject as the docker-root-working directory. This leads to problems, if there are shared librarys, like in our case. 

Would be nice, if you could add a option to the edge-tools plugin which allows a different path for the docker-root. 

Thanks. 
Toni

**Comment by rido-min** [comment]
>We need to copy the sharedNetCore sourcecode into the Docker-Build-Image

Can you elaborate why you need the source code? The binaries should be copied to the Edge-Module1 output folder as part of the project to project reference.

If you need to copy anything else to the output, like the source code, you can use an MSBuild `content` element to copy the files to the output folder:

```xml
 <ItemGroup>
    <Content Include="..\SharedNetCorelib \Class1.cs" Link="src\Class1.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```

**Comment by burgerTo** [comment]
> Can you elaborate why you need the source code? 

That's the standard  docker template (from visual studio) for .net core applications. 

```
FROM mcr.microsoft.com/dotnet/core/runtime:3.0-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /src
COPY ["ConsoleApp4/ConsoleApp4.csproj", "ConsoleApp4/"]
RUN dotnet restore "ConsoleApp4/ConsoleApp4.csproj"
COPY . .
WORKDIR "/src/ConsoleApp4"
RUN dotnet build "ConsoleApp4.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ConsoleApp4.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ConsoleApp4.dll"]
```

In the first step, a build container "mcr.microsoft.com/dotnet/core/sdk:3.0" is used. The complete sourcecode is copied into the container and the build is started in the sdk container. 
In the second step, the build artifacts are copied into the the runtime container (mcr.microsoft.com/dotnet/core/runtime) 

You could also have a look at: https://github.com/dotnet/dotnet-docker-samples/issues/84

The mentioned sample shows the same solution to build shared librarys into docker images. But in this case it works, because the docker root is the DockerFile location which is placed on solution level. 

Maybe I could rewrite the question: 
A cs-project is the root for a edge-module. It could include references to external libraries (nuget) and project references. Thats from the csproject structre design perspective. 
But the docker build process with build-root located on the project folder does not support the project-references "feature". 

I'm not sure if this problem is related to the iotedge tools. Maybe more to the general docker support in visual studio.

**Comment by SLdragon** [comment]
Hi, @burgerTo , our edge extension supported setup docker build context path.
For your scenario, you can open **module.json** file in the **Edge-Module1** project, and change the context Path to "../"

![image](https://user-images.githubusercontent.com/5545529/66632854-fe964f80-ec3b-11e9-97e1-fb89b179d2b5.png)

**Comment by rido-min** [comment]
Hi @burgerTo, for non edge related projects the convention is to copy the required project/files 
```
COPY dotnetapp/*.csproj ./dotnetapp/
COPY utils/*.csproj ./utils/
WORKDIR /app/dotnetapp
RUN dotnet restore
```

from https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/Dockerfile#L6

**Comment by SLdragon** [comment]
You can also refer troubleshoot page:

https://github.com/Microsoft/vs-azure-iot-edge-docs/wiki/Troubleshoot#4-docker-build-fails---when-reference-libraryshared-code-in-projectsolution
