### ISSUE TITLE
Default template should not include SimulatedTemperatureSensor

### ISSUE THREAD

**Issue by rido-min** [microsoft/vs-azure-iot-edge-docs#12]
File->new project->Azure Iot Edge (Linux Amd 64)
Create the project without adding any modules (Skip)

Expected. The manifest should not contain any user modules
Observed. the manifest includes the SimulatedTemperatureSensor module, 

```json
        "modules": {
          "SimulatedTemperatureSensor": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0",
              "createOptions": {}
            }
          }
        }
```

> Note there is not gesture to remove that module

**Comment by SLdragon** [comment]
Thanks for your feedback, we will fix this issue, thanks!

**Comment by SLdragon** [comment]
Hi, @rido, the extension 1.3.0 now has been released, it will not contain "SimulatedTemperatureSensor" when user skip adding module
