### ISSUE TITLE
docker build fails - when reference library/shared code in project/solution

### ISSUE THREAD

**Issue by grahamehorner** [microsoft/vs-azure-iot-edge-docs#13]
The Azure IoT Edge Module template fails to build in the module references any library or shared code file, this is due to the docker build not copying the source for the referenced project and/or shared code.

**Comment by SLdragon** [comment]
Hi, @grahamehorner , if you are build edge module project reference other libary/shared code, you should open module.json file in the Edge Module  project, and change the context Path to "../"
![image](https://user-images.githubusercontent.com/5545529/68635216-cc298c00-0532-11ea-9ffc-a4960804a046.png)

Then you should modify you Dockerfile and copy the related lib/project to the container.

Here is an related issue which you can refer:
https://github.com/microsoft/vs-azure-iot-edge-docs/issues/10

**Comment by SLdragon** [comment]
You can also refer troubleshoot page:

https://github.com/Microsoft/vs-azure-iot-edge-docs/wiki/Troubleshoot#4-docker-build-fails---when-reference-libraryshared-code-in-projectsolution

**Comment by SLdragon** [comment]
If you have any other questions, feel free to contact us
