### ISSUE TITLE
Azure IoT Edge Tools for VS 2019 - Create new IoT Edge project with a C# module - Error

### ISSUE THREAD

**Issue by jonmikeli** [microsoft/vs-azure-iot-edge-docs#14]
Hi,

I am trying to create an IoT Edge project but I get this error message:
![image](https://user-images.githubusercontent.com/22737122/68786722-8e1a8e00-0640-11ea-8179-4dcce359bd1d.png)

Steps to reproduce the error:
1- Create new project
![image](https://user-images.githubusercontent.com/22737122/68786795-adb1b680-0640-11ea-9d9c-251e85d97879.png)
2-Fill the project name and select the location
3-Create
4-Add a C# Module
![image](https://user-images.githubusercontent.com/22737122/68786630-675c5780-0640-11ea-9537-a2b4bc385271.png)

It looks like something went wrong when installing the extension/template. It seems the C# project for the Edge module (or one of the dependencies) is not found.

I have no more details (no logs, no additional information in the Output window, etc).

Configuration:
- Windows 10 x64 Enterprise
- Visual Studio 2019 Enterprise v16.3.9
- Docker Desktop 2.1.0 (39773)

I have tried to uninstall/reinstall the extension with no success.

The same extension in another laptop works properly (the OS is different though, Windows 10 x64 Pro).

Any idea of what could be the issue?
Thanks in advance for your time.

**Comment by SLdragon** [comment]
Hi, @jonmikeli , from your error message, seems like c# template is not intalled correctly, which version of the extension do you use?

You can also check your whether your visual studio workload (C# workload) installed correctly.

Here is the prerequisites to use IoT Edge extension:

https://docs.microsoft.com/en-us/azure/iot-edge/how-to-visual-studio-develop-module#prerequisites

**Comment by jonmikeli** [comment]
Hi @SLdragon,

Thank you for your email.
Find below some additional information:
 - Extension version: 1.2.0
 - I have repaired the Visual Studio install.
 - Uninstalled/installed the extension and checked the prerequisites (everything seems ok except the C SDK. Is it mandatory?)
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-visual-studio-develop-module#prerequisites
 - I can open an IoT Edge solution created by another machine.
 - However, no way to create it on the laptop where I am having issues.

**Comment by SLdragon** [comment]
Hi, @jonmikeli , please check whether the template is inside these locations:

- For C# template:


  C:\Users\[You User Name]\Documents\Visual Studio 2019\Templates\ProjectTemplates\Visual C#\azureiotedgemodule-v0.x.x.zip

- For C template:

  C:\Users\rentu.FAREAST\Documents\Visual Studio 2019\Templates\ProjectTemplates\Visual C++ Project\azureiotedgevcmodulevs16-v0.x.x.zip

You can try to clean these folder, and then recreate iot edge project.

**Comment by jonmikeli** [comment]
Hi @SLdragon,

I had both templates, cleaned the folders and tried to create a new IoT Edge project.
Always the same error.

I also upgraded the extension to 1.3.0 version. Still the same error.
Knowing I have already repaired VS and I do not have more details about the error, I do not know what else could be done. I will probably try to unzip the extension to see what are the files used and check that I have them all.

**Comment by SLdragon** [comment]
Hi, jonmikeli, please copy your Visual Studio Info in about dialog, and I will take a look.
![image](https://user-images.githubusercontent.com/5545529/69399631-d9f8c180-0d29-11ea-9cb7-65be5c430245.png)

From your error message, seems like the extension cannot find some staff which needed to create a project.

Can you also try to skip or add a marketplace module?

**Comment by jonmikeli** [comment]
Hi @SLdragon,

Thank you for your help.
![image](https://user-images.githubusercontent.com/22737122/69434336-b0e22c00-0d3d-11ea-8338-bc761e681462.png)

If you need to check the installed products, I can send you the details (via Copy Info).

Regarding the other tests:

- create an IoT Edge project with no module, OK
- create an IoT Edge project adding modules from the marketplace, OK
- create an IoT Edge project adding a C# module, KO

I have uninstalled and installed back the Azure IoT Edge Tools for VS 2019 extension.

**Comment by SLdragon** [comment]
Hi, jonmikeli, please click "Copy Info" and send me the details.

You can also check the folder below:

```
C:\Users\[Your User Name]\AppData\Local\Microsoft\VisualStudio\16.0_14515c2fExp\Extensions\Microsoft\Azure IoT Edge Tools for VS 2019\1.3.0
```

In this folder, you should see files as below:
![image](https://user-images.githubusercontent.com/5545529/69508275-45cc6b80-0f70-11ea-8c35-9a212b906903.png)

![image](https://user-images.githubusercontent.com/5545529/69508258-3816e600-0f70-11ea-883b-5741ba9a028c.png)

If you're missing some files, please let me know.

**Comment by jonmikeli** [comment]
Hi SLdragon,

Sorry for my late answer.
You will find attached my "Copy Info".
[VS2019Enterprise_CopyInfo.txt](https://github.com/microsoft/vs-azure-iot-edge-docs/files/3906813/VS2019Enterprise_CopyInfo.txt)

Regarding the folder you suggest to check, it does not exist in none of the laptops I have been using with the extension (even in those where the extension works).

I have tried to uninstall and install the extension but it does not change anything.
I have also tried to export and import the extension: same result.

You will find below the installer log.
[dd_VSIXInstaller_20191130082741_0dfc.log](https://github.com/microsoft/vs-azure-iot-edge-docs/files/3906843/dd_VSIXInstaller_20191130082741_0dfc.log)

According to it, many setup actions are skipped. The extension is installed under the following path:
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\jx5qewam.xju
`

There is no $MSBuild folder but the remaining items seem to be there (I have even one additional file, CertificateInformation.dat).
Find below the screenshots:

![image](https://user-images.githubusercontent.com/22737122/69897518-6c621c00-134d-11ea-93cc-fbbaf72883a5.png)

![image](https://user-images.githubusercontent.com/22737122/69897524-7ab03800-134d-11ea-8288-afc7b603cc69.png)

Feel free to ask if you need any further information.

**Comment by SLdragon** [comment]
Seems like the extension installed correctly. The slight difference is the VS version, I will update my VS to see whether can repro this issue.

**Comment by SLdragon** [comment]
Hi, @jonmikeli , I cannot repro your issue on my machine, do you use Teams account? If it convenient, I can remote to your computer to help you trouble shooting this.

**Comment by jonmikeli** [comment]
Hi @SLDragon,
Yes, I use MS Teams. No problem to remote (thank you by the way for proposing this). Let me check my schedule tomorrow and I will write you back.

**Comment by SLdragon** [comment]
OK, my alias is "rentu", you can find me on teams when you have spare time

**Comment by SLdragon** [comment]
Hi, @jonmikeli , have you change the template location in Visual Studio? 
You can check this from Tools -> Options -> Projects and Solutions -> Locations
![image](https://user-images.githubusercontent.com/5545529/71232074-6e574380-232b-11ea-9214-530c7dd9e934.png)

From our investigation, if your templates locations is not correct, it may also lead to "File not found" issue

**Comment by jonmikeli** [comment]
Hi @SLdragon ,

Sorry for the delay.
Thank you for your message, your investigations and your time.

I was thinking in proposing you to remote next week but after your last message, I checked my settings. It seems that my company applies policies that change the location of the "Document" folder (used in both of the template paths). After restoring the default settings, uninstalling the extension and installing it back, the IoT Edge project creation seems to work properly.
I will complete my tests in the upcoming days and keep you updated.

Thank you once more.

**Comment by jonmikeli** [comment]
Hi @SLdragon,

After many tests, everything seems to work properly after the last change you suggested.
Well done for this one ;).

Thank you for your help.
