### ISSUE TITLE
SimulatedTemperatureSensor module Will not automatically add to default project

### ISSUE THREAD

**Issue by czgtest** [microsoft/vs-azure-iot-edge-docs#15]
repro on v1.3.0-rc

1. File->new project->Azure Iot Edge (Linux Amd 64)
2. Create the project without adding any modules (Skip)
   here no SimulatedTemperatureSensor module in deployment
3. add ->new IoT edge module->select C# module
    here only add IotEdgeModule1 in deployment , SimulatedTemperatureSensor module Will not automatically add to the file again

but if user create new project with c# modules, SimulatedTemperatureSensor module will add in templated.

**Comment by SLdragon** [comment]
This is by design
