### ISSUE TITLE
Don't show output from "package manager" when create new project

### ISSUE THREAD

**Issue by czgtest** [microsoft/vs-azure-iot-edge-docs#19]
2.	Open VS or create a new Edge project
3.	Open output window, you would see the extension automatically download the simulator, and the output message would shown
4.  then output windows will switch to "Package Manager"
Expect : show output form "IoT hub"

**Comment by SLdragon** [comment]
This is by design because we cannot control "Package Manager" Window, so you should click the switch button to switch to our own output window
