### ISSUE TITLE
Default routes always added when opening visual studio

### ISSUE THREAD

**Issue by mrtncls** [microsoft/vs-azure-iot-edge-docs#22]
We've setup custom routes with custom names in our deployment.template.json.
Every time we open vs, a route named "[Modulename]ToIoTHub" is added for each module. How can we disable this feature?
We tried to use an empty string but it's not allowed by the schema.

**Comment by czgtest** [comment]
@mrtncls Thank you for bringing this to our attention. I am assigning this to the content owner for review and an update as appropriate.

**Comment by SLdragon** [comment]
Hi, @mrtncls, thanks for your feedback, now I can repro this issue, and we will fix it in next release.

**Comment by nouira** [comment]
I can confirm that we can reproduce the same problem.
Looking forward for the fix.

**Comment by SLdragon** [comment]
Hi, @mrtncls and @nouira , Visual Studio Edge Extension 1.5.0 has been released, and this issue should be fixed, if you have any other problems, feel free to contact us.

**Comment by SLdragon** [comment]
Close this issue due to already fixed, if you have any other questions, feel free to contact us
