### ISSUE TITLE
Latest extension targets older Net Core

### ISSUE THREAD

**Issue by thnk2wn** [microsoft/vs-azure-iot-edge-docs#24]
I'm curious why the latest version of the extension (1.4.0) targets .NET Core 2.1 in the project files when 3.1 is the latest on my machine. Likewise in the Dockerfile it targets:

````
FROM microsoft/dotnet:2.1-sdk AS build-env
FROM microsoft/dotnet:2.1-runtime-stretch-slim-arm32v7
````

instead of:

````
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
FROM mcr.microsoft.com/dotnet/core/runtime:3.1.1-buster-slim-arm32v7
````

Is it just a case of that was the latest when the extension was created and it hasn't been updated since? Or are their tooling or runtime requirements to use older, last verified versions?

**Comment by SLdragon** [comment]
Hi, @thnk2wn , we need to verify related dependences work fine before we update our template to new version of dotnet, and I will keep this issue open here, if there are any progresses, I would let you know

**Comment by thnk2wn** [comment]
Thanks. I'm proceeding with 3.1 as 2.1 is some 3 years old now and we have later requirements. I can add any issues I see but so far, so good.

**Comment by SLdragon** [comment]
Thank you @thnk2wn

**Comment by SLdragon** [comment]
Hi, @thnk2wn , the new version of Edge extension 1.7.0 now supported dotnet core 3.1, and thank you for your feedback
