### ISSUE TITLE
Cannot debug any debug any project from VS's UI when this is enabled

### ISSUE THREAD

**Issue by shizn** [microsoft/vs-azure-iot-edge-docs#26]
I found that whenthe extension is enabled, I'm unable to debug any project from VS's UI. Where can I log this bug?
 
Looks like someone else had the same issue once (that's actually how I found that the extension was the problem)
https://stackoverflow.com/questions/46210498/unable-to-start-debugging-the-startup-project-cannot-be-launched

**Comment by SLdragon** [comment]
Hi, @shizn , I am using VS2019 version 16.5.5 and cannot repro this issue.
Maybe the problem related some cache become corrupted for VS2019. You can try the steps below, maybe can solve your problem:

1. Reinstall the extension and restart
2. Remove MEF cache in the folder below:
```
C:\Users\[YourUserName]\AppData\Local\Microsoft\VisualStudio\16.0_14515c2f\ComponentModelCache
```
3. Repair install VS2019

**Comment by dylanbronson** [comment]
This question was asked on behalf of me, so I'll respond here!

Simply uninstalling and reinstalling the extension worked for me (VS version 16.4.2). Still odd - guess it got in some weird state somehow.

**Comment by SLdragon** [comment]
Thank you for your feedback @dylanbronson , if you still have any other problems, feel free to contact us!
