### ISSUE TITLE
Simulated Temperature Sensor not configured correctly

### ISSUE THREAD

**Issue by MichaelVach** [microsoft/vs-azure-iot-edge-docs#27]
Azure IoT Edge Tools for VS 2019 Version 1.7.0
Visual Studio 2019 Version 16.7.0 Preview 6.0

When I create a new Azure IoT Edge (Linux amd64) project and immediately add the Simulated Temperature Sensor module from Microsoft via the Azure Marketplace (all still in the configure new project wizard) the module does not get configured correctly e.g. its image location is not added to the deployment file.

If I add the Simulated Temperature Sensor after the initial project has been created all works as expected.

**Comment by konichi3** [comment]
@michaelvach Can you check if deploying tempSensor edge module from IoT Hub has the same symptom?

**Comment by konichi3** [comment]
Hi @MichaelVach 

We will close this item as we have not heard from you. Feel free to re-open or open a new issue if this still reproes and blocking you.
