### ISSUE TITLE
Problem remains: Unable to load the service index for source https://api.nuget.org/v3/index.json

### ISSUE THREAD

**Issue by hubert-associates** [microsoft/vs-azure-iot-edge-docs#3]
I was hoping that this long-standing bug would be resolved in the new 2019 version. It is not. I started from scratch after a fresh reboot,  newest VS2019preview and EdgeToolsExtension. Created a new edge project in VS2019. Below is the output from "Build IoT-Edge Modules". This problem has been around for months, with lots of guesswork solutions. Nobody seems to be able to get to the bottom of it. It needs to be fixed if we are to be able to use iot-edge with VisualStudio. In the meantime, no other option but back to Linux with iot-edge. 

It appears that the docker build (windows) is being done inside a (windows) docker container that can't reach nuget, but what to change and where? Nobody seems to know...

---snip---
Setup IoT Edge Simulator successfully.
DOCKER_HOST: 
DOCKER_TLS_VERIFY: 
DOCKER_CERT_PATH: 
Additional Env Variables: 
------ Build IoT Edge Modules started: Platform: Windows Amd64, Configuration: Release ------
The deployment manifest is generated at C:\Users\tt\source\repos\P2\AzureIotEdgeApp3\AzureIotEdgeApp3\config\deployment.windows-amd64.json
docker inspect registry --format='{{.State.Running}}'
Error: No such object: registry
docker run -d -p 5000:5000 --restart always --name registry registry:2
Unable to find image 'registry:2' locally
2: Pulling from library/registry
docker: no matching manifest for windows/amd64 10.0.17763 in the manifest list entries.
See 'docker run --help'.
docker build --rm -f "C:\Users\tt\source\repos\P2\AzureIotEdgeApp3\IotEdgeModuleCs1\Dockerfile.windows-amd64" -t localhost:5000/iotedgemodulecs1:0.0.1-windows-amd64  "C:\Users\tt\source\repos\P2\AzureIotEdgeApp3\IotEdgeModuleCs1"
Sending build context to Docker daemon  690.2kB
Step 1/10 : FROM microsoft/dotnet:2.1-sdk AS build-env
 ---> b45d6ac11a2b
Step 2/10 : WORKDIR /app
 ---> Using cache
 ---> 614ab20fdc13
Step 3/10 : COPY *.csproj ./
 ---> 454642614a37
Step 4/10 : RUN dotnet restore
 ---> Running in 87190a7a2ca8
C:\Program Files\dotnet\sdk\2.1.603\NuGet.targets(119,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\app\IotEdgeModuleCs1.csproj]
C:\Program Files\dotnet\sdk\2.1.603\NuGet.targets(119,5): error :   No such host is known [C:\app\IotEdgeModuleCs1.csproj]
The command 'cmd /S /C dotnet restore' returned a non-zero code: 1
[ERROR]: The command 'cmd /S /C dotnet restore' returned a non-zero code: 1

**Comment by SLdragon** [comment]
Hi, @hubert-associates , thanks for your feedback, from your error message, maybe it is a network issue when the template try to restore nuget packages.
Please check your network connection and firewall settings and try again.

**Comment by hubert-associates** [comment]
Thanks. It is not a network issue. Same issue in several different networks. Nuget works well on all my other projects from the same machine. I'm thinking that it is an Docker-win10-desktop (edge edition, newest) thing: docker build is happening inside a docker container. What must I add to the config? There are lots of people grappling with this, no conclusive fix found yet AFAIK. Still searching (and working on Linux to make progress)

**Comment by SLdragon** [comment]
Hi, @hubert-associates , thanks for you information? Are there some threads in docker repo to track this issue?

**Comment by SLdragon** [comment]
Hi, @hubert-associates, I found there is an issue in nuget which discuss this issue, some people mentioned that restart docker may solve the problem.
https://github.com/NuGet/Home/issues/5358

**Comment by SLdragon** [comment]
Close due to external issue
