### ISSUE TITLE
VS2022 Support?

### ISSUE THREAD

**Issue by chull434** [microsoft/vs-azure-iot-edge-docs#35]
Hi, 

Is there any plans for this tool to be migrated over and to support VS 2022?

or is vs code more the future direction?

thanks,
~whiskers434

**Comment by martin-weber** [comment]
+1. Same question.

**Comment by konichi3** [comment]
Thanks for the questions and feedback. It is currently in our backlog to support Edge extension in VS2022.
We will share the update.

May I know if VS Code is a viable solution for you? Are there are any scenarios that don't work in VS Code?

**Comment by martin-weber** [comment]
Hi @konichi3,

Thanks for your answer. For me as a C# developer VS 2022 is the preferred tool. It is more convenient to stay in VS 2022 to debug my service that communicates with the edge module together by running both project using multiple startup projects. 

Running the services in VS 2022 and the edge modules in VS Code is not convenient. Also not sure if there might be any issues with shared library projects then when we compile them from both tools.

**Comment by axeli-a** [comment]
I'm in the same situation as @martin-weber -- having to use a combination of VS2022 and VSCode isn't really a realistic option in the long-run.
Do you have any sort of time-line for when you'd be starting to work on this?

**Comment by buurenmi** [comment]
Hi Great to hear that the edge extention support is on the backlog. Is there a time plan for this item? 
Regards Michiel.

**Comment by konichi3** [comment]
Thank you all for quick responses. Your feedbacks are valuable to us. Unfortunately we don't have concrete timeline yet as there are various factors like UX integration, testing in addition to coding that we need to assess.

Please stay tuned for further updates from us.

**Comment by Andkago** [comment]
Up this one :)

**Comment by mrtncls** [comment]
Can't wait to start using vs2022 on our iotedge project

**Comment by Steve0212a** [comment]
following - I need this too

**Comment by Metal-Mighty** [comment]
Subscribing as well, my team is waiting for the updated addon to switch our application to .Net 6/VS 2022 🙂

**Comment by konichi3** [comment]
Hi everyone.

Thank you very much for your feedback. Given the magnitude of impacts, we are currently prioritizing this work item and continuing to work on this. 

While we do not have any committed timeline yet, I want to share the status and iterate that this is our top priority and will keep this thread updated.

thank you!

**Comment by mvximvs** [comment]
hey @konichi3 Thanks for you feedback. I'm actually following this tutorial  [ Develop and deploy custom IoT Edge modules](https://docs.microsoft.com/en-us/learn/paths/develop-deploy-custom-iot-edge-modules/) and the developer experience with VSCode is awful. The debugger its very laggy  and everything is just very slow. By the way I appreciate a LOT all the extensions to work with IoT /Azure/Docker on vscode, that is a really good point. 
I'll be waiting for this extension on VS2022 ❤️

**Comment by mndarren** [comment]
> +1. Same question.

+1 Same question

**Comment by konichi3** [comment]
Hi all,

We are excited to announce that [IoT Edge extension for Visual Studio 2022](https://marketplace.visualstudio.com/items?itemName=vsc-iot.vs17iotedgetools) is now avaialble to download.

Please share us the feedback!

**Comment by mndarren** [comment]
Just installed it and the **incompatible** issue is **gone**! Thanks so much!

**Comment by Steve0212a** [comment]
thank you so much.  I have successfully updated everything in my sln to .net 6.

**Comment by konichi3** [comment]
Thanks everyone for the comment and feedback. We will close the issue but feel free to create new issue if needed.
