### ISSUE TITLE
Unable to deploy to devices since CLoud Explorer is Retired

### ISSUE THREAD

**Issue by Andkago** [microsoft/vs-azure-iot-edge-docs#36]
In 2019 the way to deploy was using Cloud Explorer. Now the cloud explorer is retired without a substitute, how to do this now?

**Comment by konichi3** [comment]
Hi @Andkago 

We have recently [updated the do](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-visual-studio-develop-module?view=iotedge-2020-11#check-your-tools-version)c to describe alternative way to manage modules.

Closing the issue.
