### ISSUE TITLE
Announcing the Azure IoT Edge tool offerings in maintenance mode

### ISSUE THREAD

**Issue by konichi3** [microsoft/vs-azure-iot-edge-docs#42]
As Azure IoT Edge product continues to evolve with [new features](https://github.com/Azure/iotedge/releases) and updated version to the LTS 1.4 (Long term service), one of our goals is to ensure we deliver consistent ways to develop, debug and test Azure IoT Edge modules on various version of Azure IoT Edge.

To best support the consistency across heterogenous developer environments and requirements, we have now published [a new documentation](https://aka.ms/newiotedgedev) which describes how to develop, debug and test Azure IoT Edge modules using command line interface.
This is a new recommended way to develop Azure IoT Edge modules.

With this new way, effective immediately, we are putting these product offering in maintenance mode where we are making minimum updates/changes to the products moving forward. Note that these products will continue to be available via either Marketplace or GitHub release pages.

These product are:
• [Azure IoT Edge extension to Visual Studio Code](https://github.com/microsoft/vscode-azure-iot-edge/)
• [Azure IoT Edge extension to Visual Studio 2019/2022](https://github.com/microsoft/vs-azure-iot-edge-docs/)
• [IoTEdgeHubDev tool](https://github.com/Azure/iotedgehubdev/)
• [Azure DevOps pipeline for IoT Edge](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-continuous-integration-continuous-deployment-classic?view=iotedge-2020-11)

thank you,
Azure IoT Edge team

**Comment by fgheysels** [comment]
So, to be sure, this means that creating iotedge modules via future versions of Visual Studio won't be possible anymore via the GUI ?
We're now creating iotedge modules via the 'Add new IoT Edge module' menu option:
![image](https://user-images.githubusercontent.com/3605786/207549056-8e6ebde1-3fda-4eaf-9f4d-d4781605cf6f.png)
Which presents then this dialog:
![image](https://user-images.githubusercontent.com/3605786/207549180-30c72b44-e872-4efe-b712-03136779e896.png)

So, this is being deprecated ?

**Comment by fgheysels** [comment]
A lot of questions here.  If this is not the correct place to ask them, please point me to the correct place :)

The [documentation on the GitHub project site](https://github.com/microsoft/vs-azure-iot-edge-docs) of the [VS.NET extension](https://marketplace.visualstudio.com/items?itemName=vsc-iot.vs17iotedgetools&ssr=false#overview) now refers to the CLI way of creating modules, and this points to the [Visual Code way of creating IoT Edge projects and modules](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-vs-code-develop-module?view=iotedge-1.4&branch=pr-en-us-203829&tabs=csharp&pivots=iotedge-dev-cli).
Does this mean that VS Code will be the preferred way to create IoT Edge solutions and VS.NET will no longer be supported in the future ?

**Comment by konichi3** [comment]
Hi @fgheysels 

Thank you for the feedback. Here is the current status of the Azure IoT Edge development tooling.

- Currently, we don't have plans to remove VSCode and VS extensions from the marketplace and you can continue to develop modules using extension
- We recommend CLI way to develop edge module for both VSCode and VS projects
- We are aware of the issue where CLI way for creating a new IoT Edge solution with VS project is not working properly and we are currently working on changes.

thanks!
Azure IoT Edge team

**Comment by fgheysels** [comment]
Thanks for the feedback @konichi3 

Additionally, I wonder if it is possible for developers to create custom templates for creating an IOT Edge module, and that those custom templates appear in the 'Add module' dialog box in VS.NET when creating a new iotedge module.
Can't seem to find any documentation on that.

**Comment by konichi3** [comment]
Unfortunately, not. These templates are managed and stored through Microsoft owned repository.

**Comment by rido-min** [comment]
The dotnet template has been updated to target 6.0 (although it's only available using the CLI and not from VS)
https://github.com/Azure/dotnet-template-azure-iot-edge-module

**Comment by fgheysels** [comment]
I see that in that project template, a new module client instance is created in the background-servcie.  Going along that route, that would mean that you would create a moduleclient instance per background-service that you have.
Is that a good way to do this ?  What are the best pracices around the moduleClient class ?   I thought it would be best to have only a single ModuleClient instance per IoT Edge module ?

**Comment by rido-min** [comment]
hi @fgheysels 

you are right, each EdgeModule should have a single instance of ModuleClient.

Can you file an issue in https://github.com/Azure/dotnet-template-azure-iot-edge-module ? I'm thinking to use a Singleton in the sample.

**Comment by tank104** [comment]
I am trying to understand this - so just to amke sure.

The link that you provided to use (https://learn.microsoft.com/en-us/azure/iot-edge/tutorial-develop-for-linux?view=iotedge-1.4&tabs=csharp&pivots=iotedge-dev-cli) is for VSCode CLI.

On that same site in the menu is steps to develop in Visual Studio using Dev tool cli: https://learn.microsoft.com/en-us/azure/iot-edge/how-to-visual-studio-develop-module?view=iotedge-1.4&pivots=iotedge-dev-cli however all the instructions talk about creating solution and modules using the plugin.

So are we supposed to do everything in VSCode now?  or is that Visual Studio instructions out of date, or am I just misunderstanding this?

**Comment by tank104** [comment]
I am going a bit around in circles on this.
Is EFLOW also being deprecated?  If not can we get an updated version of how to debug on it: https://learn.microsoft.com/en-us/azure/iot-edge/tutorial-develop-for-linux-on-windows?view=iotedge-1.4

The only instructions are for Visual Studio, and the tools are obviously being deprecated/maintenance mode.

**Comment by tank104** [comment]
(Moved this to enw thread since this is closed: https://github.com/microsoft/vs-azure-iot-edge-docs/issues/46)
