### ISSUE TITLE
Older Versions of Azure IoT Edge Tools Visual Studio Extensions

### ISSUE THREAD

**Issue by scout208** [microsoft/vs-azure-iot-edge-docs#45]
I'm wondering if it would be possible to access older versions of the Azure IoT Edge Tools Visual Studio extension. I noticed in the most recent update to v2.0.8 it restricted support to IoTEdge v1.4. We have some devices in the field that are still running 1.1 that we won't be able to upgrade to 1.4 until next year. I'd like to still be able to write and update modules for those in the meantime, but I can't do that with the latest version of Azure IoT Edge Tools. Is there any place I could get the older releases?

**Comment by konichi3** [comment]
IoT Edge 1.1 is no longer servicing branch and 1.4 is the only active servicing branch. We encourage you to upgrade to 1.4 IoT Edge.
