### ISSUE TITLE
Debugging disabled for .NET Core projects after installing plugin

### ISSUE THREAD

**Issue by heing** [microsoft/vs-azure-iot-edge-docs#5]
After installing the extension version 1.1 on VS 2019, I cannot debug or start .NET Core projects anymore. The "Start Debugging" and "Start Without Debugging" options are grayed out in the Debug menu and when right-clicking on the project. .NET Framework console application works as expected.

If  I disable the extension and restart Visual Studio, debugging works again.

**Comment by SLdragon** [comment]
Hi, @heing, thanks for your feedback, I install 1.1 and try to debug dotnetcore project, it works fine. 
![image](https://user-images.githubusercontent.com/5545529/63081375-0906d680-bf76-11e9-9eb3-ca322a95afec.png)

Can you share us more detailed information about your project and your VS version, I will take try, thanks!

**Comment by heing** [comment]
The project is the default .NET Core console application. Visual Studio version is 16.1.5 (Professional). See other installed extensions in attached screen shot below:

![image](https://user-images.githubusercontent.com/1460235/63090237-f9c65f80-bf5a-11e9-8acd-ffda7ea52eeb.png)

**Comment by heing** [comment]
I have upgraded Visual Studio to version 16.2.2 and it seemed to solve the issue.
