### ISSUE TITLE
Modules in subfolders don't start when debugging IoT Edge project

### ISSUE THREAD

**Issue by candersonio** [microsoft/vs-azure-iot-edge-docs#6]
**Environment:**
Windows 10 Pro, Version 1803, Build 17134.885
Microsoft Visual Studio Enterprise 2019 Version 16.2.2
Azure IoT Edge Tools for VS 2019 Version 1.1
iotedgehubdev Version 0.10.0

**Issue:**
When trying to debug an IoT Edge project, any module that is not in the root of the solution is not starting during the debug. This is only referring to the location of the project in the solution, the location of the project on disk is the same whether or not the module is in a subfolder or not.

**Expected Behavior:**
I would expect that every module that is part of the the IoT Edge project should be started regardless of its location. **Also**, I would expect an error anytime there is a module that is not starting when debugging the project.

**Repro:**
1. Create an IotEdge solution with default parameters.
2. Add a C# with default parameters
3. Add a second C# with default parameters.
4. Debug AzureIotEdgeApp1.
That should debug the solution with the two modules both starting up:
![image](https://user-images.githubusercontent.com/28271572/63107627-e3b0a300-bf4a-11e9-8fd5-7ebfd6402867.png)
Startup Logs:
```
======================Preparing IoT Edge Runtime======================
iotedgehubdev modulecred -l -m "IotEdgeModule1|IotEdgeModule2"
...
```
5. Create a new folder in the solution.
6. Drag IoTEdgeModule1 into the newly created folder.
7. Debug AzureIotEdgeApp1.
That will result in only IoTEdgeModule2 starting during debug.
![image](https://user-images.githubusercontent.com/28271572/63107651-f0cd9200-bf4a-11e9-90a5-bd3ce2c236cf.png)
Startup Logs:
```
======================Preparing IoT Edge Runtime======================
iotedgehubdev modulecred -l -m "IotEdgeModule2"
...
```

**Comment by SLdragon** [comment]
Thanks for your feedback, I tested it, maybe it is a bug, and we will fix it in the future release

**Comment by SLdragon** [comment]
Hi, @candersonio 
1.2.0 has been released and now it support debug edge modules in solution folder, you can find the latest extension here:
https://marketplace.visualstudio.com/items?itemName=vsc-iot.vs16iotedgetools
