### ISSUE TITLE
Azure Marketplace broken?

### ISSUE THREAD

**Issue by jkewley** [microsoft/vs-azure-iot-edge-docs#7]
**Environment**
VS 2019 16.2.2
Azure IoT Tools for VS 2019 v 1.1

**Project**
C# module for windows AMD64

**Error**
When creating a new project, the wizard pops up to create the first module, Choosing **show modules from Azure Marketplace** displays the error "**_Cannot load module list from marketplace, please try again_**".  Trying to add a new module to an existing project shows the same error when Azure Marketplace is selected.

Fiddler shows the API call is returning a Json payload with the marketplace details.

**Comment by SLdragon** [comment]
Thank you for your feedback, we have already publish a hotfix to fix this issue, you can update to 1.1.1 to solve the problem.
